[theme]
background = "#04051D"
primary = "#F1F1F1"
secondary = "#DCDCDC"
title = "#23A9AF"
playing = "#0D0F0E"
playing_selected = "#2E7081"
playing_bg = "#23A9AF"
highlight = "#23A9AF"
highlight_bg = "#000000"
error = "#FFE4E4"
error_bg = "#A50000"
statusbar = "#000000"
statusbar_progress = "#23A9AF"
statusbar_bg = "#23A9AF"
cmdline = "#CBFFDE"
cmdline_bg = "#444444"